"""Project constants."""

BACKGROUND_MODE_NONE = "none"
BACKGROUND_MODE_SHARED_SMOOTH = "shared_smooth"
DEFAULT_BURN_IN = 20
DEFAULT_CG_MAXITER = 300
DEFAULT_CG_RTOL = 1e-6
DEFAULT_CONVERGENCE_EPSILON = 1e-3
DEFAULT_ENFORCE_NONNEGATIVE_IMAGE = False
DEFAULT_INTENSITY_SCALE = 255.0
DEFAULT_MAX_SAMPLES = 80
DEFAULT_MODULATION_DEPTH = 1.0
DEFAULT_PHASE_DEG = 0.0
DEFAULT_SEED = 123
DEFAULT_SHARED_PRECISION = False
DEFAULT_TEST_PATTERN_SHAPE = (263, 263)
DEFAULT_WIDEFIELD_INDEX = 0
PAPER_ORIENTATIONS_DEG = (-30.0, 30.0, 90.0)
SAMPLING_MODE_BLOCK_AVERAGE = "block_average"
SAMPLING_MODE_POINT_SAMPLE = "point_sample"
